$(function(){
  $(".favorite-star-icon").on('click',function(){
    $(".favorite-star-icon").css('display','none')
    $(".favorite-star-icon2").css('display','block')
  })
  $(".favorite-star-icon2").on('click',function(){
    $(".favorite-star-icon2").css('display','none')
    $(".favorite-star-icon").css('display','block')
  })
})